default: all

# Add more for other apps
all: calculator # calculator app2 app3 etc

# Copy and paste for different apps
calculator: calculator.c
	gcc -o calculator calculator.c cs50.c

# Removes app
clean:
	rm -f calculator